import 'notification_template.dart';

const List<NotificationTemplate> mockNotifications = [
  NotificationTemplate(
    id: 'comeback_001',
    category: NotificationCategories.comeback,
    title: 'Your bottles are waiting',
    body: 'A calm color pour is ready whenever you are.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'comeback_002',
    category: NotificationCategories.comeback,
    title: 'Sort a little color',
    body: 'One quiet level can turn the whole board tidy.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'comeback_003',
    category: NotificationCategories.comeback,
    title: 'Back to the pour',
    body: 'Line up the colors and clear another bottle set.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'comeback_004',
    category: NotificationCategories.comeback,
    title: 'A fresh sort is open',
    body: 'Those colors will feel great once they settle.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'comeback_005',
    category: NotificationCategories.comeback,
    title: 'Ready for a clean board?',
    body: 'Pour, match, and watch the bottles fall into place.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'comeback_006',
    category: NotificationCategories.comeback,
    title: 'Take a color break',
    body: 'A few smooth pours can reset the whole puzzle.',
    payloadRoute: '/home',
  ),
  NotificationTemplate(
    id: 'comeback_007',
    category: NotificationCategories.comeback,
    title: 'A gentle puzzle is ready',
    body: 'Return to the bottles and sort at your own pace.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'comeback_008',
    category: NotificationCategories.comeback,
    title: 'Colors need a nudge',
    body: 'Open a level and make the next perfect pour.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'level_progress_001',
    category: NotificationCategories.levelProgress,
    title: 'Next level is ready',
    body: 'New bottles, new colors, same satisfying sort.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'level_progress_002',
    category: NotificationCategories.levelProgress,
    title: 'Keep the streak smooth',
    body: 'Clear one more board and move your level forward.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'level_progress_003',
    category: NotificationCategories.levelProgress,
    title: 'Your next pour is close',
    body: 'Finish the next level with a tidy color stack.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'level_progress_004',
    category: NotificationCategories.levelProgress,
    title: 'Another board unlocked',
    body: 'The next bottle puzzle is waiting for a clean solve.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'level_progress_005',
    category: NotificationCategories.levelProgress,
    title: 'Level progress is calling',
    body: 'Pour the top colors and watch the board open up.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'level_progress_006',
    category: NotificationCategories.levelProgress,
    title: 'One level at a time',
    body: 'A neat solution is hiding in the next few pours.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'level_progress_007',
    category: NotificationCategories.levelProgress,
    title: 'Move the colors forward',
    body: 'Solve another set and keep your level climb steady.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'level_progress_008',
    category: NotificationCategories.levelProgress,
    title: 'Your board is ready',
    body: 'Start the next level and sort every bottle clean.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'hint_reminder_001',
    category: NotificationCategories.hintReminder,
    title: 'Need a gentle hint?',
    body: 'A smart pour can reveal the path through the colors.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'hint_reminder_002',
    category: NotificationCategories.hintReminder,
    title: 'Hints can help',
    body: 'If the bottles feel tangled, let a hint guide one pour.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'hint_reminder_003',
    category: NotificationCategories.hintReminder,
    title: 'Find the quiet move',
    body: 'A hint can spot the color that should move next.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'hint_reminder_004',
    category: NotificationCategories.hintReminder,
    title: 'Stuck on a bottle?',
    body: 'Use a hint and turn a messy stack into a clean plan.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'hint_reminder_005',
    category: NotificationCategories.hintReminder,
    title: 'A helpful pour is nearby',
    body: 'Hints point to the move that keeps colors flowing.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'hint_reminder_006',
    category: NotificationCategories.hintReminder,
    title: 'Untangle the colors',
    body: 'One hint can make the next bottle click into place.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'hint_reminder_007',
    category: NotificationCategories.hintReminder,
    title: 'Let the board breathe',
    body: 'A hint can open the space you need for a smooth solve.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'hint_reminder_008',
    category: NotificationCategories.hintReminder,
    title: 'Try one guided move',
    body: 'The right color pour can make the whole level easier.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'coin_reward_001',
    category: NotificationCategories.coinReward,
    title: 'Coins are one level away',
    body: 'Solve a bottle board and build your shop stash.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'coin_reward_002',
    category: NotificationCategories.coinReward,
    title: 'Earn coins with a clean sort',
    body: 'Every completed level adds more shine to your wallet.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'coin_reward_003',
    category: NotificationCategories.coinReward,
    title: 'Fill the coin jar',
    body: 'A satisfying solve can bring you closer to a new style.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'coin_reward_004',
    category: NotificationCategories.coinReward,
    title: 'More coins, more looks',
    body: 'Clear a color puzzle and save toward the shop.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'coin_reward_005',
    category: NotificationCategories.coinReward,
    title: 'Your next reward is simple',
    body: 'Sort the bottles, finish the level, collect the coins.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'coin_reward_006',
    category: NotificationCategories.coinReward,
    title: 'A tidy board pays off',
    body: 'Coins come with every calm level completion.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'coin_reward_007',
    category: NotificationCategories.coinReward,
    title: 'Save for your favorite skin',
    body: 'A few solved bottles can move you closer.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'coin_reward_008',
    category: NotificationCategories.coinReward,
    title: 'Coins love clean colors',
    body: 'Finish another sort and grow your collection.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'shop_reminder_001',
    category: NotificationCategories.shopReminder,
    title: 'Visit the shop',
    body: 'Bottle skins, fills, and themes are ready to browse.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'shop_reminder_002',
    category: NotificationCategories.shopReminder,
    title: 'Refresh your puzzle look',
    body: 'Open the shop and pick a style for your next sort.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'shop_reminder_003',
    category: NotificationCategories.shopReminder,
    title: 'New style mood?',
    body: 'Check bottles, contents, and themes before your next level.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'shop_reminder_004',
    category: NotificationCategories.shopReminder,
    title: 'Your collection is waiting',
    body: 'Spend coins on a bottle style that fits your board.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'shop_reminder_005',
    category: NotificationCategories.shopReminder,
    title: 'Make the pour yours',
    body: 'Browse shop styles and return to sorting refreshed.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'shop_reminder_006',
    category: NotificationCategories.shopReminder,
    title: 'A new look can help',
    body: 'Choose a theme or fill style for a cleaner puzzle mood.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'shop_reminder_007',
    category: NotificationCategories.shopReminder,
    title: 'Check your unlocked styles',
    body: 'Your next bottle setup might already be in the shop.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'shop_reminder_008',
    category: NotificationCategories.shopReminder,
    title: 'Shop before you sort',
    body: 'A fresh bottle look makes each color pour feel new.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'theme_unlock_001',
    category: NotificationCategories.themeUnlock,
    title: 'Theme goals are close',
    body: 'Solve levels, collect coins, and unlock a new backdrop.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'theme_unlock_002',
    category: NotificationCategories.themeUnlock,
    title: 'Set a calmer board',
    body: 'A new theme can change the whole color sort mood.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'theme_unlock_003',
    category: NotificationCategories.themeUnlock,
    title: 'Change the puzzle glow',
    body: 'Browse themes and give your bottles a fresh stage.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'theme_unlock_004',
    category: NotificationCategories.themeUnlock,
    title: 'Your next theme awaits',
    body: 'Earn coins through levels and unlock a new color mood.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'theme_unlock_005',
    category: NotificationCategories.themeUnlock,
    title: 'Try a different atmosphere',
    body: 'Themes make every pour feel a little more personal.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'theme_unlock_006',
    category: NotificationCategories.themeUnlock,
    title: 'A fresh board color calls',
    body: 'Open the shop and see which theme fits your next solve.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'theme_unlock_007',
    category: NotificationCategories.themeUnlock,
    title: 'Unlock a softer scene',
    body: 'Level rewards can move you closer to a new theme.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'theme_unlock_008',
    category: NotificationCategories.themeUnlock,
    title: 'Your board can shine',
    body: 'Shop themes bring a fresh feel to every bottle puzzle.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'bottle_style_001',
    category: NotificationCategories.bottleStyle,
    title: 'New bottle style?',
    body: 'Pick a bottle skin and make each pour feel polished.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'bottle_style_002',
    category: NotificationCategories.bottleStyle,
    title: 'Dress up the bottles',
    body: 'Your colors deserve a clean new glass shape.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'bottle_style_003',
    category: NotificationCategories.bottleStyle,
    title: 'Bottle skins are waiting',
    body: 'Browse styles before sorting your next color stack.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'bottle_style_004',
    category: NotificationCategories.bottleStyle,
    title: 'Change the silhouette',
    body: 'A new bottle skin can make the same puzzle feel fresh.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'bottle_style_005',
    category: NotificationCategories.bottleStyle,
    title: 'Pour with a new look',
    body: 'Try a bottle style that matches your favorite theme.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'bottle_style_006',
    category: NotificationCategories.bottleStyle,
    title: 'Your shelf needs variety',
    body: 'Coins can unlock more bottle shapes for your levels.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'bottle_style_007',
    category: NotificationCategories.bottleStyle,
    title: 'A clean bottle refresh',
    body: 'Open the shop and choose a style for the next sort.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'bottle_style_008',
    category: NotificationCategories.bottleStyle,
    title: 'Make each bottle yours',
    body: 'Find a skin that makes the color stacks stand out.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'fill_style_001',
    category: NotificationCategories.fillStyle,
    title: 'Try a new fill style',
    body: 'Change how colors settle inside each bottle.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'fill_style_002',
    category: NotificationCategories.fillStyle,
    title: 'Fresh contents, same calm pour',
    body: 'Browse fill styles before your next level.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'fill_style_003',
    category: NotificationCategories.fillStyle,
    title: 'Let the colors flow differently',
    body: 'A new fill style can make every sorted stack pop.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'fill_style_004',
    category: NotificationCategories.fillStyle,
    title: 'Update the color texture',
    body: 'Pick a fill style that makes the bottles feel fresh.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'fill_style_005',
    category: NotificationCategories.fillStyle,
    title: 'Your pours can sparkle',
    body: 'Check fill styles and give each color a new finish.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'fill_style_006',
    category: NotificationCategories.fillStyle,
    title: 'A smoother color look',
    body: 'Unlock a fill style and return to the board refreshed.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'fill_style_007',
    category: NotificationCategories.fillStyle,
    title: 'Contents matter',
    body: 'Choose how every color layer rests in the bottle.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'fill_style_008',
    category: NotificationCategories.fillStyle,
    title: 'Give colors a new finish',
    body: 'Shop fill styles before your next satisfying solve.',
    payloadRoute: '/shop',
  ),
  NotificationTemplate(
    id: 'challenge_001',
    category: NotificationCategories.challenge,
    title: 'Ready for a tidy challenge?',
    body: 'Solve a board with careful pours and clean color stacks.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'challenge_002',
    category: NotificationCategories.challenge,
    title: 'Can you clear this set?',
    body: 'Watch the top colors and make each move count.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'challenge_003',
    category: NotificationCategories.challenge,
    title: 'Puzzle focus time',
    body: 'One bottle at a time, sort the colors into order.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'challenge_004',
    category: NotificationCategories.challenge,
    title: 'A neat solve is possible',
    body: 'Plan the empty space and pour your way through.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'challenge_005',
    category: NotificationCategories.challenge,
    title: 'Try a careful board',
    body: 'Each color layer has a place. Find it.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'challenge_006',
    category: NotificationCategories.challenge,
    title: 'Make every pour count',
    body: 'The next level rewards patience and clean sorting.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'challenge_007',
    category: NotificationCategories.challenge,
    title: 'Bottle logic is calling',
    body: 'Use the empty slots well and finish the set.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'challenge_008',
    category: NotificationCategories.challenge,
    title: 'A calm challenge awaits',
    body: 'Pour the colors into place without rushing the board.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'daily_puzzle_001',
    category: NotificationCategories.dailyPuzzle,
    title: 'Daily color sort',
    body: 'Open a fresh bottle puzzle and start with a clean pour.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'daily_puzzle_002',
    category: NotificationCategories.dailyPuzzle,
    title: 'Today needs one solve',
    body: 'A short color puzzle is ready for a quiet break.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'daily_puzzle_003',
    category: NotificationCategories.dailyPuzzle,
    title: 'Your daily pour is ready',
    body: 'Sort one level and enjoy the clean finish.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'daily_puzzle_004',
    category: NotificationCategories.dailyPuzzle,
    title: 'A fresh board today',
    body: 'New bottle stacks are waiting for the right order.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'daily_puzzle_005',
    category: NotificationCategories.dailyPuzzle,
    title: 'One puzzle, many colors',
    body: 'Settle in and sort the daily bottle mix.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'daily_puzzle_006',
    category: NotificationCategories.dailyPuzzle,
    title: 'Daily sorting moment',
    body: 'A clean level is a nice way to reset the day.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'daily_puzzle_007',
    category: NotificationCategories.dailyPuzzle,
    title: 'Your color break is here',
    body: "Pour a few bottles and clear today's puzzle mood.",
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'daily_puzzle_008',
    category: NotificationCategories.dailyPuzzle,
    title: 'Start today with a sort',
    body: 'Move the top colors and make the board clean.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'undo_boost_001',
    category: NotificationCategories.undoBoost,
    title: 'Undo keeps it calm',
    body: 'If a pour feels wrong, step back and try a cleaner move.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'undo_boost_002',
    category: NotificationCategories.undoBoost,
    title: 'No rush on the board',
    body: 'Use undo to rethink a bottle and keep sorting smoothly.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'undo_boost_003',
    category: NotificationCategories.undoBoost,
    title: 'Fix one pour',
    body: 'Undo can turn a tangled stack back into a plan.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'undo_boost_004',
    category: NotificationCategories.undoBoost,
    title: 'Try, undo, solve',
    body: 'The path gets clearer when every color has space.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'undo_boost_005',
    category: NotificationCategories.undoBoost,
    title: 'Undo is there',
    body: 'A single step back can save a beautiful solve.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'undo_boost_006',
    category: NotificationCategories.undoBoost,
    title: 'Make the careful move',
    body: 'Pour with confidence. Undo helps if the board shifts.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'undo_boost_007',
    category: NotificationCategories.undoBoost,
    title: 'Keep your solve tidy',
    body: 'Undo a messy pour and line the colors up again.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'undo_boost_008',
    category: NotificationCategories.undoBoost,
    title: 'A cleaner route is near',
    body: 'Step back once and find the pour that opens the level.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'extra_moves_001',
    category: NotificationCategories.extraMoves,
    title: 'Need a few extra moves?',
    body: 'Return to the board and give the colors more room.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'extra_moves_002',
    category: NotificationCategories.extraMoves,
    title: 'Almost solved?',
    body: 'Extra moves can help finish a tight bottle puzzle.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'extra_moves_003',
    category: NotificationCategories.extraMoves,
    title: 'When the board is close',
    body: 'A few more moves can turn near-solved into sorted.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'extra_moves_004',
    category: NotificationCategories.extraMoves,
    title: 'Give the colors space',
    body: 'Extra moves can help when the last bottles get tight.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'extra_moves_005',
    category: NotificationCategories.extraMoves,
    title: 'Finish the last pour',
    body: 'Open the level and rescue a close solve.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'extra_moves_006',
    category: NotificationCategories.extraMoves,
    title: 'A little room helps',
    body: 'Extra moves can keep your color sort flowing.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'extra_moves_007',
    category: NotificationCategories.extraMoves,
    title: 'Tight board?',
    body: 'Come back and use every move with care.',
    payloadRoute: '/game',
  ),
  NotificationTemplate(
    id: 'extra_moves_008',
    category: NotificationCategories.extraMoves,
    title: 'One more chance to sort',
    body: 'Extra moves can bring the last colors home.',
    payloadRoute: '/game',
  ),
];
